service: onestophalalbot
frameworkVersion: '2'
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
    TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}

functions:
  oneStopHalalAlert:
    handler: handler.oneStopHalalAlert
    events:
      - schedule: rate(4 hours)